name: Superstitious Protection

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  schedule:
    # Run daily to proactively protect upcoming numbers
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  superstitious-protection:
    runs-on: ubuntu-latest
    name: Protect from unlucky numbers
    permissions:
      issues: write
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Superstitious GitHub Action
        id: superstitious
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: 'superstitious.yml'

      - name: Report Results
        run: |
          echo "## Superstitious Protection Results" >> $GITHUB_STEP_SUMMARY
          echo "- Issues created: ${{ steps.superstitious.outputs.issues-created }}" >> $GITHUB_STEP_SUMMARY
          echo "- Issues cleared: ${{ steps.superstitious.outputs.issues-cleared }}" >> $GITHUB_STEP_SUMMARY
          echo "- Next safe number: ${{ steps.superstitious.outputs.next-safe-number }}" >> $GITHUB_STEP_SUMMARY