name: Superstitious Protection

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  schedule:
    # Run every hour to proactively protect upcoming numbers
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      clearing_mode:
        description: 'Run in clearing mode to fix existing unlucky numbers'
        required: false
        default: false
        type: boolean
      dry_run:
        description: 'Run in dry-run mode (no actual changes)'
        required: false
        default: false
        type: boolean

jobs:
  superstitious-protection:
    runs-on: ubuntu-latest
    name: Protect from unlucky numbers
    permissions:
      issues: write
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Superstitious GitHub Action
        id: superstitious
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: 'superstitious.yml'
          clearing-mode: ${{ github.event.inputs.clearing_mode || 'false' }}
          dry-run: ${{ github.event.inputs.dry_run || 'false' }}

      - name: Report Results
        run: |
          echo "## Superstitious Protection Results" >> $GITHUB_STEP_SUMMARY
          echo "- Issues created: ${{ steps.superstitious.outputs.issues-created }}" >> $GITHUB_STEP_SUMMARY
          echo "- Issues cleared: ${{ steps.superstitious.outputs.issues-cleared }}" >> $GITHUB_STEP_SUMMARY
          echo "- Next safe number: ${{ steps.superstitious.outputs.next-safe-number }}" >> $GITHUB_STEP_SUMMARY